// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: simulation.proto

package sim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Simulator_SubmitSimulation_FullMethodName = "/sim.Simulator/SubmitSimulation"
	Simulator_WorkerStream_FullMethodName     = "/sim.Simulator/WorkerStream"
)

// SimulatorClient is the client API for Simulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulatorClient interface {
	SubmitSimulation(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SimulationResponse], error)
	WorkerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, WorkerMessage], error)
}

type simulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulatorClient(cc grpc.ClientConnInterface) SimulatorClient {
	return &simulatorClient{cc}
}

func (c *simulatorClient) SubmitSimulation(ctx context.Context, in *SimulationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SimulationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Simulator_ServiceDesc.Streams[0], Simulator_SubmitSimulation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SimulationRequest, SimulationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Simulator_SubmitSimulationClient = grpc.ServerStreamingClient[SimulationResponse]

func (c *simulatorClient) WorkerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, WorkerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Simulator_ServiceDesc.Streams[1], Simulator_WorkerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, WorkerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Simulator_WorkerStreamClient = grpc.BidiStreamingClient[WorkerMessage, WorkerMessage]

// SimulatorServer is the server API for Simulator service.
// All implementations must embed UnimplementedSimulatorServer
// for forward compatibility.
type SimulatorServer interface {
	SubmitSimulation(*SimulationRequest, grpc.ServerStreamingServer[SimulationResponse]) error
	WorkerStream(grpc.BidiStreamingServer[WorkerMessage, WorkerMessage]) error
	mustEmbedUnimplementedSimulatorServer()
}

// UnimplementedSimulatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulatorServer struct{}

func (UnimplementedSimulatorServer) SubmitSimulation(*SimulationRequest, grpc.ServerStreamingServer[SimulationResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubmitSimulation not implemented")
}
func (UnimplementedSimulatorServer) WorkerStream(grpc.BidiStreamingServer[WorkerMessage, WorkerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method WorkerStream not implemented")
}
func (UnimplementedSimulatorServer) mustEmbedUnimplementedSimulatorServer() {}
func (UnimplementedSimulatorServer) testEmbeddedByValue()                   {}

// UnsafeSimulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulatorServer will
// result in compilation errors.
type UnsafeSimulatorServer interface {
	mustEmbedUnimplementedSimulatorServer()
}

func RegisterSimulatorServer(s grpc.ServiceRegistrar, srv SimulatorServer) {
	// If the following call pancis, it indicates UnimplementedSimulatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Simulator_ServiceDesc, srv)
}

func _Simulator_SubmitSimulation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SimulationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulatorServer).SubmitSimulation(m, &grpc.GenericServerStream[SimulationRequest, SimulationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Simulator_SubmitSimulationServer = grpc.ServerStreamingServer[SimulationResponse]

func _Simulator_WorkerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimulatorServer).WorkerStream(&grpc.GenericServerStream[WorkerMessage, WorkerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Simulator_WorkerStreamServer = grpc.BidiStreamingServer[WorkerMessage, WorkerMessage]

// Simulator_ServiceDesc is the grpc.ServiceDesc for Simulator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Simulator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sim.Simulator",
	HandlerType: (*SimulatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitSimulation",
			Handler:       _Simulator_SubmitSimulation_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WorkerStream",
			Handler:       _Simulator_WorkerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "simulation.proto",
}
