services:
  # Gateway (Go)
  gateway:
    build: 
      context: ./backend/gateway
      dockerfile: Dockerfile.gateway
    container_name: server 
    image: bsp-gate
    ports:
      - "8080:8080"
    networks:
      - bsp_net
    depends_on:
      - server
  
  # Server/Proxy (Go)
  server:
    build: 
      context: ./backend/server
      dockerfile: Dockerfile.server
    container_name: server 
    image: bsp-serve
    ports:
      - "8080:8080"
    networks:
      - bsp_net
    depends_on:
      - runner
      - mongodb

  # Single runner module actually running Vivarium Interface (Python). Uses Flask to get input data from Go server
  runner:
    build:
      context: ./backend/runner
      dockerfile: Dockerfile.runner 
    container_name: runner 
    image: bsp-run
    ports:
      - "5000:5000"
    networks:
      - bsp_net
    depends_on: 
      - mongodb 
      - server 

  # MongoDb with ChangeStreams enabled (used for communication between server and runner)
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    networks:
      - bsp_net
    ports:
      - "27017:27017"
    restart: always
    command: [ "mongod", "--replSet", "rs0" ]  # Enable Replica Set
    volumes:
      # - mongo_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro  # Auto-init

  # Express.js handler for ChangeStream events/connection
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      - bsp_net
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

networks:
  bsp_net:
    driver: bridge