services:
  go-gateway:
      build: ./go-gateway
      ports:
        - "8080:8080"
      depends_on:
        - python-simulator

  python-simulator:
    build: ./python-simulator
    ports:
      - "5000:5000"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    networks:
      - bsp_net
    ports:
      - "27017:27017"
    restart: always
    command: [ "mongod", "--replSet", "rs0" ]  # Enable Replica Set
    volumes:
      # - mongo_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro  # Auto-init

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      - bsp_net
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

  gateway:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Server.Dockerfile
    image: bsp-gate
    container_name: gateway
    networks:
      - bsp_net
    depends_on:
      - mongodb
    command: |
      uv run python -c "import time; time.sleep(100)"

  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Server.Dockerfile
    image: bsp-serve
    container_name: server
    networks:
      - bsp_net
    depends_on:
      - mongodb
    command: |
      uv run python backend/listener.py

networks:
  bsp_net:
    driver: bridge