name: biosimulator-processes
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - readdy
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - poetry
  # - readdy
  # - pymem3dg