[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython",
    "numpy"
]
build-backend = "setuptools.build_meta"

[project]
name = "biosimulator-processes"
version = "0.3.21"  # LATEST: latest stable is 0.3.8; LEGACY: latest stable pypi release: 0.1.2(biosimulator-processes) ... 0.2.5(as biosimulators-processes)
description = "Core implementations of process-bigraph.composite.Process aligning with BioSimulators simulator tools."
authors = [{name = "Alex Patrie", email = "alexanderpatrie@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "process-bigraph",
    "pip-autoremove",
    "seaborn",
    "ipython",
    "toml",
    "pyyaml",
    "python-dotenv",
    "requests",
    "h5py",
    "python-libsbml",
]

[project.optional-dependencies]
cobra = ["cobra>=0.29.1"]
copasi = ["copasi-basico>=0.83"]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.0",
]
docs = [
    "nbsphinx>=0.9.7",
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.0.2",
]
membrane = ["pymem3dg>=0.0.7"]
quantum = ["pyscf>=2.8.0", "qiskit-ibm-runtime>=0.37.0", "qiskit-nature>=0.7.2"]
smoldyn = ["smoldyn>=2.73", "simulariumio>=1.12.0"]
tellurium = ["tellurium>=2.2.10"]
vcell = ["pyvcell>=0.0.1"]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "nbsphinx>=0.9.7",
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.0",
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.0.2",
]

[tool.setuptools]
packages = [
    "bsp",
    "tests"
]




