[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython",
    "numpy"
]
build-backend = "setuptools.build_meta"

[project]
name = "biosimulator-processes"
version = "0.3.21"  # LATEST: latest stable is 0.3.8; LEGACY: latest stable pypi release: 0.1.2(biosimulator-processes) ... 0.2.5(as biosimulators-processes)
description = "Core implementations of process-bigraph.composite.Process aligning with BioSimulators simulator tools."
authors = [{name = "Alex Patrie", email = "alexanderpatrie@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "pip-autoremove",
    "seaborn",
    "ipython",
    "toml",
    "pyyaml",
    "python-dotenv",
    "requests",
    "h5py",
    "python-libsbml",
    "numpy==1.26.4",
    "process-bigraph==0.0.27",
    "vivarium-interface>=0.0.3",
    "typer>=0.12.5",
    "pydantic>=2.9.2",
    "gunicorn>=23.0.0",
]

[project.optional-dependencies]
cobra = ["cobra>=0.29.1"]
copasi = ["copasi-basico>=0.83"]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.0",
]
docs = [
    "griffe>=1.6.2",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.9",
    "mkdocstrings[python]>=0.29.0",
    "nbsphinx>=0.9.7",
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.0.2",
]
membrane = ["pymem3dg>=0.0.7"]
quantum = ["pyscf>=2.8.0", "qiskit-ibm-runtime>=0.37.0", "qiskit-nature>=0.7.2"]
tellurium = ["tellurium>=2.2.10"]
vcell = ["pyvcell>=0.0.1"]
server = [
    "fastapi>=0.115.11",
    "flask>=3.1.0",
    "grpcio>=1.71.0",
    "grpcio-tools>=1.71.0",
    "pymongo>=4.11.3",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "nbsphinx>=0.9.7",
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.0",
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.0.2",
]

[tool.setuptools]
packages = [
    "bsp",
    "backend",
    "tests"
]

# [tool.ruff]
# target-version = "py39"
# line-length = 120
# fix = true
# lint.select = [
#   "F",    # Pyflakes (undefined names, unused imports, etc.)
#   "E",    # Pycodestyle errors
#   "W",    # Pycodestyle warnings
#   "B",    # Bugbear (common bugs)
# ]
# lint.ignore = [
#   "E501",   # Line too long
#   "B008",   # Function calls in argument defaults (common in CLIs)
# ]
# 
# [tool.ruff.format]
# preview = true
# 
# [tool.ruff.per-file-ignores]
# "tests/*" = ["S101"]  # Ignore use of `assert` in tests





