syntax = "proto3";

import "google/protobuf/struct.proto";

package sim;

option go_package = "github.com/vivarium-collective/biosimulator-processes/backend/proto;sim";

service Simulator {
  rpc SubmitSimulation (SimulationRequest) returns (stream SimulationResponse);
}

message SimulationRequest {
  string job_id = 1;
  string timestamp = 2;
  int32 duration = 3;
  google.protobuf.Struct state = 4;
  string status = 5;
}

message SimulationResponse {
  string job_id = 1;
  string status = 2;
  string timestamp = 3;
  google.protobuf.Struct results = 4;
  int32 interval_id = 5;
}
