openapi: 3.1.0
info:
  title: compare-api
  version: 1.0.0
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /get-process-attributes:
    get:
      summary: Get Process Attributes
      operationId: get-process-attributes
      parameters:
      - name: process_name
        in: query
        required: true
        schema:
          type: string
          title: 'Name of the process type; i.e: copasi, tellurium, etc.'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessAttributes'
        '404':
          description: Unable to get attributes for specified simulator process.
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /run-ode-comparison:
    post:
      summary: Run A Simulator Comparison
      operationId: run-comparison
      parameters:
      - name: biomodel_id
        in: query
        required: true
        schema:
          type: string
          title: Biomodel ID of to be run by the simulator composite
      - name: simulators
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
          title: Simulators to Compare
          default:
          - tellurium
          - copasi
          - amici
      - name: duration
        in: query
        required: true
        schema:
          type: integer
          title: Duration
      - name: num_steps
        in: query
        required: true
        schema:
          type: integer
          title: Number of Steps
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODEComparisonResult'
        '404':
          description: Unable to run comparison
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ODEComparisonResult:
      properties:
        duration:
          type: integer
          title: Duration
        num_steps:
          type: integer
          title: Num Steps
        simulators:
          items:
            type: string
          type: array
          title: Simulators
        outputs:
          items:
            $ref: '#/components/schemas/SimulatorProcessOutput'
          type: array
          title: Outputs
        timestamp:
          type: string
          title: Timestamp
      type: object
      required:
      - duration
      - num_steps
      - simulators
      - outputs
      - timestamp
      title: ODEComparisonResult
    OutputData:
      properties:
        name:
          type: string
          title: Name
        value:
          type: number
          title: Value
      type: object
      required:
      - name
      - value
      title: OutputData
    ProcessAttributes:
      properties:
        name:
          type: string
          title: Name
        initial_state:
          type: object
          title: Initial State
        inputs:
          type: object
          title: Inputs
        outputs:
          type: object
          title: Outputs
      type: object
      required:
      - name
      - initial_state
      - inputs
      - outputs
      title: ProcessAttributes
    SimulatorProcessOutput:
      properties:
        process_id:
          type: string
          title: Process Id
        simulator:
          type: string
          title: Simulator
        data:
          items:
            $ref: '#/components/schemas/OutputData'
          type: array
          title: Data
      type: object
      required:
      - process_id
      - simulator
      - data
      title: SimulatorProcessOutput
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
