// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cpu": {
            "get": {
                "description": "Returns CPU statistics in JSON format",
                "produces": [
                    "application/json"
                ],
                "summary": "Get CPU usage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.CPUResponse"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "Returns real-time system metrics via Server-Sent Events (SSE)",
                "produces": [
                    "text/event-stream"
                ],
                "summary": "Stream CPU and Memory data",
                "responses": {
                    "200": {
                        "description": "SSE Stream started",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/items": {
            "get": {
                "description": "Retrieves an item with name and price",
                "produces": [
                    "application/json"
                ],
                "summary": "Get an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item Name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Item Price",
                        "name": "price",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/memory": {
            "get": {
                "description": "Returns Memory statistics in JSON format",
                "produces": [
                    "application/json"
                ],
                "summary": "Get Memory usage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.MemoryResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.CPUResponse": {
            "type": "object",
            "properties": {
                "idle": {
                    "type": "number"
                },
                "system": {
                    "type": "number"
                },
                "user": {
                    "type": "number"
                }
            }
        },
        "main.MemoryResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                },
                "used_percent": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "System Metrics API",
	Description:      "This API provides CPU and Memory usage information via REST and SSE",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
