# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runner/runner.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'runner/runner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13runner/runner.proto\x12\x06runner\"C\n\rSimulationJob\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x10\n\x08\x64ocument\x18\x03 \x01(\t\"k\n\x10SimulationResult\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x13\n\x0binterval_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07results\x18\x05 \x01(\t2X\n\x10SimulationRunner\x12\x44\n\rRunSimulation\x12\x15.runner.SimulationJob\x1a\x18.runner.SimulationResult(\x01\x30\x01\x42SZQgithub.com/vivarium-collective/biosimulator-processes/backend/proto/runner;runnerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runner.runner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZQgithub.com/vivarium-collective/biosimulator-processes/backend/proto/runner;runner'
  _globals['_SIMULATIONJOB']._serialized_start=31
  _globals['_SIMULATIONJOB']._serialized_end=98
  _globals['_SIMULATIONRESULT']._serialized_start=100
  _globals['_SIMULATIONRESULT']._serialized_end=207
  _globals['_SIMULATIONRUNNER']._serialized_start=209
  _globals['_SIMULATIONRUNNER']._serialized_end=297
# @@protoc_insertion_point(module_scope)
