# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import backend.runner.simulation_pb2 as simulation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitSimulation = channel.unary_stream(
                '/sim.Simulator/SubmitSimulation',
                request_serializer=simulation__pb2.SimulationRequest.SerializeToString,
                response_deserializer=simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.SubmitJob = channel.unary_unary(
                '/sim.Simulator/SubmitJob',
                request_serializer=simulation__pb2.SimulationRequest.SerializeToString,
                response_deserializer=simulation__pb2.JobAck.FromString,
                _registered_method=True)


class SimulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitSimulation': grpc.unary_stream_rpc_method_handler(
                    servicer.SubmitSimulation,
                    request_deserializer=simulation__pb2.SimulationRequest.FromString,
                    response_serializer=simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=simulation__pb2.SimulationRequest.FromString,
                    response_serializer=simulation__pb2.JobAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sim.Simulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sim.Simulator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Simulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sim.Simulator/SubmitSimulation',
            simulation__pb2.SimulationRequest.SerializeToString,
            simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sim.Simulator/SubmitJob',
            simulation__pb2.SimulationRequest.SerializeToString,
            simulation__pb2.JobAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
