FROM golang:latest AS builder  

# TODO: replace repo-level Go configs (.mod and .sum) with package-level configs, for each Go microservice (gateway and server)
WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download 

COPY ./backend .

RUN go build -o main . 

FROM debian:bullseye-slim AS runtime 

WORKDIR /app 

COPY --from=builder /app/main . 

CMD ["./main"]
