// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: runner.proto

package runner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulationRunner_RunSimulation_FullMethodName = "/runner.SimulationRunner/RunSimulation"
)

// SimulationRunnerClient is the client API for SimulationRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulationRunnerClient interface {
	RunSimulation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SimulationJob, SimulationResult], error)
}

type simulationRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationRunnerClient(cc grpc.ClientConnInterface) SimulationRunnerClient {
	return &simulationRunnerClient{cc}
}

func (c *simulationRunnerClient) RunSimulation(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SimulationJob, SimulationResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimulationRunner_ServiceDesc.Streams[0], SimulationRunner_RunSimulation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SimulationJob, SimulationResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationRunner_RunSimulationClient = grpc.BidiStreamingClient[SimulationJob, SimulationResult]

// SimulationRunnerServer is the server API for SimulationRunner service.
// All implementations must embed UnimplementedSimulationRunnerServer
// for forward compatibility.
type SimulationRunnerServer interface {
	RunSimulation(grpc.BidiStreamingServer[SimulationJob, SimulationResult]) error
	mustEmbedUnimplementedSimulationRunnerServer()
}

// UnimplementedSimulationRunnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulationRunnerServer struct{}

func (UnimplementedSimulationRunnerServer) RunSimulation(grpc.BidiStreamingServer[SimulationJob, SimulationResult]) error {
	return status.Errorf(codes.Unimplemented, "method RunSimulation not implemented")
}
func (UnimplementedSimulationRunnerServer) mustEmbedUnimplementedSimulationRunnerServer() {}
func (UnimplementedSimulationRunnerServer) testEmbeddedByValue()                          {}

// UnsafeSimulationRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationRunnerServer will
// result in compilation errors.
type UnsafeSimulationRunnerServer interface {
	mustEmbedUnimplementedSimulationRunnerServer()
}

func RegisterSimulationRunnerServer(s grpc.ServiceRegistrar, srv SimulationRunnerServer) {
	// If the following call pancis, it indicates UnimplementedSimulationRunnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulationRunner_ServiceDesc, srv)
}

func _SimulationRunner_RunSimulation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimulationRunnerServer).RunSimulation(&grpc.GenericServerStream[SimulationJob, SimulationResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationRunner_RunSimulationServer = grpc.BidiStreamingServer[SimulationJob, SimulationResult]

// SimulationRunner_ServiceDesc is the grpc.ServiceDesc for SimulationRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.SimulationRunner",
	HandlerType: (*SimulationRunnerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunSimulation",
			Handler:       _SimulationRunner_RunSimulation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "runner.proto",
}
