name: Tests

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@main
      with:
        ref: main
        # fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'

    - name: Install project and dependencies
      run: |
        python -m pip install --upgrade pip && pip install .

    - name: Install additional dependencies
      run: |
        pip install nbconvert pytest pytest-cov

    - name: Test with pytest
      run: |
        pytest
